name: Test
on:
  push:
    branches: [master]
    paths-ignore: ['**/*.md']
  pull_request:
    branches: [master]
    paths-ignore: ['**/*.md']
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel-versions: ["^6.0", "^7.0", "^8.0", "^9.0", "^10.0", "^11.0"]
        php-versions: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        exclude:
          - laravel-versions: "^6.0"
            php-versions: "8.1"
          - laravel-versions: "^6.0"
            php-versions: "8.2"
          - laravel-versions: "^6.0"
            php-versions: "8.3"

          - laravel-versions: "^7.0"
            php-versions: "7.2"
          - laravel-versions: "^7.0"
            php-versions: "7.3"
          - laravel-versions: "^7.0"
            php-versions: "7.4"
          - laravel-versions: "^7.0"
            php-versions: "8.0"
          - laravel-versions: "^8.0"
            php-versions: "7.2"
          - laravel-versions: "^8.0"
            php-versions: "8.2"
          - laravel-versions: "^8.0"
            php-versions: "8.3"
          - laravel-versions: "^9.0"
            php-versions: "7.2"
          - laravel-versions: "^9.0"
            php-versions: "7.3"
          - laravel-versions: "^9.0"
            php-versions: "7.4"
          - laravel-versions: "^9.0"
            php-versions: "8.3"
          - laravel-versions: "^10.0"
            php-versions: "7.2"
          - laravel-versions: "^10.0"
            php-versions: "7.3"
          - laravel-versions: "^10.0"
            php-versions: "7.4"
          - laravel-versions: "^10.0"
            php-versions: "8.0"
          - laravel-versions: "^11.0"
            php-versions: "7.2"
          - laravel-versions: "^11.0"
            php-versions: "7.3"
          - laravel-versions: "^11.0"
            php-versions: "7.4"
          - laravel-versions: "^11.0"
            php-versions: "8.0"
          - laravel-versions: "^11.0"
            php-versions: "8.1"
    name: PHP ${{ matrix.php-versions }} with Laravel ${{ matrix.laravel-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            ~/.cache/composer/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Laravel
        run: composer require "laravel/framework:${{ matrix.laravel-versions }}" --no-update

      - name: Composer Install
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run test suite
        run: composer test:dist